### ISSUE TITLE
activation BT

### ISSUE THREAD

**Issue by guigur** [ecoticket/ecoticket-android#1]
le Bluetooth s'active lors du démarrage de l'application et non lors du transfert de fichier.
Il ne se désactive pas lorsque l'on quitte l'application

EDIT (by JN) : Mettre l'activation du bluetooth lors du transfert du fichier mais garder en mémoire si le bluetooth etait activé avant le transfert de fichier ou pas (histoire d'eviter de desactiver le bluetooth du gars si il l'avait allumé volontairement).

**Comment by gaellast** [comment]
fix
