### ISSUE TITLE
creation de compte avec une adresse email invalide

### ISSUE THREAD

**Issue by guigur** [ecoticket/ecoticket-android#5]
on peux créer un nouveau compte avec une adresse email sans @ ou ndd.
ex: 
test                     (est accepté mais ne devrais pas)
jambon@test     (ne devrais pas être accepter non plus)
jambon@test.fr  (doit être accepter)

**Comment by gaellast** [comment]
pour le moment on cache l'email car le serveur ne demande pas l'email.
