### ISSUE TITLE
changer l'email dans l'onglet "Nous Contacter"

### ISSUE THREAD

**Issue by guigur** [ecoticket/ecoticket-android#7]
l'email dans l’onglet "nous contacter" est ecoticket@yopmail.fr. Il faut soit faire un formulaire de contact dans l'application, soit changer l’adresse email et ne laisser que le contact email avec ecoticketfrance@gmail.com

**Comment by gaellast** [comment]
fait. changement de l'adresse email en ecoticketfrance@gmail.com
